### ISSUE TITLE
setup-ruby failing consistently on Ubuntu

### ISSUE THREAD

**Issue by ydnar** [actions/setup-ruby#67]
```shell
Run actions/setup-ruby@v1
11
sudo ln -sf /Users/runner/hostedtoolcache/Ruby/2.7.0/x64/bin/ruby /usr/bin/ruby
12
ln: /usr/bin/ruby: Operation not permitted
13
(node:1108) UnhandledPromiseRejectionWarning: Error: The process 'sudo' failed with exit code 1
14
    at ExecState._setResult (/Users/runner/runners/2.169.0/work/_actions/actions/setup-ruby/v1/node_modules/@actions/exec/lib/toolrunner.js:547:25)
15
    at ExecState.CheckComplete (/Users/runner/runners/2.169.0/work/_actions/actions/setup-ruby/v1/node_modules/@actions/exec/lib/toolrunner.js:530:18)
16
    at ChildProcess.<anonymous> (/Users/runner/runners/2.169.0/work/_actions/actions/setup-ruby/v1/node_modules/@actions/exec/lib/toolrunner.js:430:27)
17
    at ChildProcess.emit (events.js:210:5)
18
    at maybeClose (internal/child_process.js:1021:16)
19
    at Socket.<anonymous> (internal/child_process.js:430:11)
20
    at Socket.emit (events.js:210:5)
21
    at Pipe.<anonymous> (net.js:659:12)
22
(node:1108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
23
(node:1108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by eregon** [comment]
Same as https://github.com/actions/setup-ruby/issues/63

This action needs to update `v1` be the latest release `v1.1.1`.

**Comment by ydnar** [comment]
Is `v1.1.1` pre-release or stable? The README still references`setup-ruby@v1`.

**Comment by eregon** [comment]
Until this is solved I can recommend https://github.com/ruby/setup-ruby
