### ISSUE TITLE
Error on macOS

### ISSUE THREAD

**Issue by alexisbronchart** [actions/setup-ruby#81]
I'm trying to setup ruby on a macOS workflow:

```
- uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
```
 
which gives this error:

```
 Run actions/setup-ruby@v1 1s
(node:992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Run actions/setup-ruby@v1
sudo ln -sf /Users/runner/hostedtoolcache/Ruby/2.7.1/x64/bin/ruby /usr/bin/ruby
ln: /usr/bin/ruby: Operation not permitted
(node:992) UnhandledPromiseRejectionWarning: Error: The process 'sudo' failed with exit code 1
    at ExecState._setResult (/Users/runner/work/_actions/actions/setup-ruby/v1/node_modules/@actions/exec/lib/toolrunner.js:547:25)
    at ExecState.CheckComplete (/Users/runner/work/_actions/actions/setup-ruby/v1/node_modules/@actions/exec/lib/toolrunner.js:530:18)
    at ChildProcess.<anonymous> (/Users/runner/work/_actions/actions/setup-ruby/v1/node_modules/@actions/exec/lib/toolrunner.js:430:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
[...]
```
Do I need anything else to make this work?

**Comment by alexisbronchart** [comment]
Oops just found https://github.com/actions/setup-ruby/issues/18
